spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/db01
    username: postgres
    password: qwerty123
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml
    default-schema: public

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: emailMessage:org.example.dto.EmailMessage
    topics:
      - name: finish-registration
      - name: create-documents
      - name: send-documents
      - name: send-ses
      - name: credit-issued
      - name: statement-denied

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  api_docs:
    enabled: true

server:
  port: 8081

scoring:
  service:
    url: http://localhost:8080/calculator/calc

pre-scoring:
  service:
    url: http://localhost:8080/calculator/offers

