springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  api_docs:
    enabled: true

server:
  port: 8989

statement:
  service:
    url-statement: http://localhost:8888/statement
    url-offer: http://localhost:8888/statement/offer
deal:
  service:
    url-registration: http://localhost:8081/deal/calculate
    url-document: http://localhost:8081/deal/document


