springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  api_docs:
    enabled: true

server:
  port: 8989

statement:
  service:
    url-statement: http://localhost:8888/statement
deal:
  service:
    url-deal:http://localhost:8081/deal


