name: CI

on:
  push:
    branches:
      - develope/feature/devops

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout код
        uses: actions/checkout@v3

      - name: Настроить JDK
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Запустить тесты с покрытием
        run: mvn clean verify jacoco:report
